CREATE DATABASE IF NOT EXISTS $MARIADB_DB;
CREATE USER IF NOT EXISTS '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PWD';
GRANT ALL PRIVILEGES ON $MARIADB_DB.* TO '$MARIADB_USER'@'%';
FLUSH PRIVILEGES;
ALTER USER '$MARIADB_ADMIN_USER'@'localhost' IDENTIFIED BY '$MARIADB_ADMIN_PWD';